# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_DataMhs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# mengimport toolkit core dan widget GUI dari PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets

# class ui_form denga param object
class Ui_Form(object):
    # fungsi untuk mensetup form tampilan
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(548, 603)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 430, 471, 143))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # code untuk mensetting font, fontsize, dan font style
        # disini nama objectnya adalah 'lbl_nimMhs' 
        # dari widget Label
        self.lbl_nimMhs = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nimMhs.setFont(font)
        self.lbl_nimMhs.setObjectName("lbl_nimMhs")
        self.verticalLayout_3.addWidget(self.lbl_nimMhs)

        # code untuk mensetting font, fontsize, dan font style
        # disini nama objectnya adalah 'lbl_namaMhs' 
        # dari widget Label
        self.lbl_namaMhs = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_namaMhs.setFont(font)
        self.lbl_namaMhs.setObjectName("lbl_namaMhs")
        self.verticalLayout_3.addWidget(self.lbl_namaMhs)

        # code untuk mensetting font, fontsize, dan font style
        # disini nama objectnya adalah 'lbl_jurusanMhs' 
        # dari widget Label
        self.lbl_jurusanMhs = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_jurusanMhs.setFont(font)
        self.lbl_jurusanMhs.setObjectName("lbl_jurusanMhs")
        self.verticalLayout_3.addWidget(self.lbl_jurusanMhs)

        # code untuk mensetting font, fontsize, dan font style
        # disini nama objectnya adalah 'lbl_noTelpMhs' 
        # dari widget Label
        self.lbl_noTelpMhs = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_noTelpMhs.setFont(font)
        self.lbl_noTelpMhs.setObjectName("lbl_noTelpMhs")
        self.verticalLayout_3.addWidget(self.lbl_noTelpMhs)

        # code untuk Form Layout -> Vertical Layout
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # code untuk menset nama object dari widget vertical layout
        # disini nama objectnya 'ledit_nimMhs'
        # dengan widget Line Edit
        self.ledit_nimMhs = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledit_nimMhs.setObjectName("ledit_nimMhs")
        self.verticalLayout_2.addWidget(self.ledit_nimMhs)

        # code untuk menset nama object dari widget vertical layout
        # disini nama objectnya 'ledit_namaMhs'
        # dengan widget Line Edit
        self.ledit_namaMhs = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledit_namaMhs.setObjectName("ledit_namaMhs")
        self.verticalLayout_2.addWidget(self.ledit_namaMhs)

        # code untuk menset nama object dari widget vertical layout
        # disini nama objectnya 'ledit_jurusanMhs'
        # dengan widget Line Edit
        self.ledit_jurusanMhs = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledit_jurusanMhs.setObjectName("ledit_jurusanMhs")
        self.verticalLayout_2.addWidget(self.ledit_jurusanMhs)

        # code untuk menset nama object dari widget vertical layout
        # disini nama objectnya 'ledit_noTelpMhs'
        # dengan widget Line Edit
        self.ledit_noTelpMhs = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ledit_noTelpMhs.setObjectName("ledit_noTelpMhs")
        self.verticalLayout_2.addWidget(self.ledit_noTelpMhs)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)

        # code untuk Form Layout --> Horizontal Layout
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        # code untuk mensetting button, font button, dan font button style
        # disini nama objectnya adalah 'btn_tambah'
        # dengan widget Push Button
        self.btn_tambah = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setBold(True)
        font.setWeight(75)
        self.btn_tambah.setFont(font)
        self.btn_tambah.setObjectName("btn_tambah")
        self.horizontalLayout.addWidget(self.btn_tambah)

        # code untuk mensetting button, font button, dan font button style
        # disini nama objectnya adalah 'btn_edit'
        # dengan widget Push Button
        self.btn_edit = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setBold(True)
        font.setWeight(75)
        self.btn_edit.setFont(font)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)

        # code untuk mensetting button, font button, dan font button style
        # disini nama objectnya adalah 'btn_clear'
        # dengan widget Push Button
        self.btn_clear = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout.addWidget(self.btn_clear)

        # code untuk mensetting button, font button, dan font button style
        # disini nama objectnya adalah 'btn_clear_2'
        # dengan widget Push Button
        self.btn_clear_2 = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear_2.setFont(font)
        self.btn_clear_2.setObjectName("btn_clear_2")
        self.horizontalLayout.addWidget(self.btn_clear_2)

        # code untuk Form Layout --> Vertical Layout
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 20, 471, 401))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # code untuk mensetting nama font, font size, font style
        # pada widget label di dalam vertical layout
        self.lbl_dataMhs = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Iosevka")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dataMhs.setFont(font)
        self.lbl_dataMhs.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dataMhs.setObjectName("lbl_dataMhs")
        self.verticalLayout_4.addWidget(self.lbl_dataMhs)

        # code untuk mensetting object name dari 'plte_dataMhs'
        # pada widget plain edit text di dalam vertical layout
        self.plte_dataMhs = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        self.plte_dataMhs.setObjectName("plte_dataMhs")
        self.verticalLayout_4.addWidget(self.plte_dataMhs)

        # memanggil fungsi retranslateUi dari param Form
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    # fungsi retranslate untuk memberi nama pada komponen widgetnya
    # seperti label, button, dan window tittlenya
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_nimMhs.setText(_translate("Form", "NIM"))
        self.lbl_namaMhs.setText(_translate("Form", "Nama"))
        self.lbl_jurusanMhs.setText(_translate("Form", "Jurusan"))
        self.lbl_noTelpMhs.setText(_translate("Form", "No. Telp"))
        self.btn_tambah.setText(_translate("Form", "TAMBAH"))
        self.btn_edit.setText(_translate("Form", "EDIT"))
        self.btn_clear.setText(_translate("Form", "CLEAR"))
        self.btn_clear_2.setText(_translate("Form", "HAPUS"))
        self.lbl_dataMhs.setText(_translate("Form", "DATA MAHASISWA"))

# jika file dijalankan langsung, maka jalankan fungsi main()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
